"""Agent pack: a folder an agent installs as a custom tool.

Produces ``plugin.yaml``, ``tools/<name>.py``, ``env.example`` and a README.

The tool is **one self-contained Python file**. It embeds the standard-library
runner, the workflow, the capabilities and the source of every single-file
engine, so the agent's Python needs nothing installed for it.

The file is written for how such agents read a tool: a plain synchronous
function named exactly like the tool, real ``str/int/float/bool`` annotations
(no ``from __future__ import annotations``), and the description in the
docstring.
"""

from __future__ import annotations

import json
import re
from typing import Any

import yaml

from ..bundle import Bundle
from ._common import FILE_FORMS, approve_text, gated, is_file, ordered_inputs

TOOL_NAME_RE = re.compile(r"^[a-z][a-z0-9_]{2,63}$")
ANNOTATION = {"integer": "int", "number": "float", "boolean": "bool"}

TEMPLATE = '''# Generated by the workflow factory. Edit the source workflow, not this file.
# Self-contained: needs only the Python standard library (plus any packages listed
# in the pack README for the engines it contains).
import hashlib
import json
import os
import sys
import tempfile
import time
import types
from pathlib import Path

_PORTABLE_SOURCE = __PORTABLE__
_BUNDLE = json.loads(__BUNDLE__)
_GATED = __GATED__
_runner = None


def _load_runner():
    global _runner
    if _runner is None:
        module = types.ModuleType("studio_portable")
        sys.modules["studio_portable"] = module
        exec(compile(_PORTABLE_SOURCE, "studio_portable.py", "exec"), module.__dict__)
        _runner = module
    return _runner


def _home():
    digest = hashlib.sha1(json.dumps(_BUNDLE, sort_keys=True).encode()).hexdigest()[:8]
    base = Path(os.environ.get("STUDIO_TOOL_HOME") or Path(tempfile.gettempdir()) / "studio_tools")
    root = base / "__NAME__" / digest
    for relative, source in _BUNDLE["engines"].items():
        target = root / relative
        if not target.exists():
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source, encoding="utf-8")
    return root


def _truthy(value):
    # an agent may hand over "false" as text, and bool("false") is True
    if isinstance(value, str):
        return value.strip().lower() in ("true", "1", "yes", "y")
    return bool(value)


def _invoke(values, approve):
    approve = _truthy(approve)
    try:
        runner = _load_runner()
        if _GATED and not approve:
            return {
                "status": "needs_approval",
                "gated_steps": _GATED,
                "message": __APPROVE_MESSAGE__,
            }
        root = _home()
        bases = {
            cid: (Path(p) if Path(p).is_absolute() else root / p) for cid, p in _BUNDLE["bases"].items()
        }
        workdir = root / "runs" / time.strftime("%Y%m%d_%H%M%S")
        result = runner.run(
            _BUNDLE["workflow"], _BUNDLE["capabilities"], bases,
            {k: v for k, v in values.items() if v is not None}, workdir,
            approve=lambda step, cap: approve, files=runner.FilePolicy.from_env(),
        )
        return {"status": "ok", "outputs": result.outputs, "run_folder": str(workdir)}
    except Exception as error:  # the agent should read the reason, not a traceback
        return {"status": "error", "error": f"{type(error).__name__}: {error}"}


__FUNCTION__
'''


def _annotation(spec: dict[str, Any]) -> str:
    return ANNOTATION.get(spec["type"], "str")


def _function(name: str, bundle: Bundle) -> str:
    params: list[str] = []
    lines: list[str] = []
    for input_name, spec in ordered_inputs(bundle):
        annotation = _annotation(spec)
        if spec.get("required") and "default" not in spec:
            params.append(f"{input_name}: {annotation}")
        elif "default" in spec and annotation in {"int", "float", "bool", "str"} and isinstance(
            spec["default"], (int, float, bool, str)
        ):
            params.append(f"{input_name}: {annotation} = {spec['default']!r}")
        else:
            params.append(f"{input_name}: {annotation} = None")
        detail = spec.get("description", "")
        if spec["type"] == "enum":
            detail = f"One of: {', '.join(map(str, spec.get('values', [])))}. {detail}".strip()
        elif is_file(spec):
            detail = f"A file, given as {FILE_FORMS} (pass an object as JSON text). {detail}".strip()
        elif spec["type"] in {"list", "object", "any"}:
            detail = f"JSON text. {detail}".strip()
        lines.append(f"        {input_name}: {detail}".rstrip())
    if gated(bundle):
        params.append("approve: bool = False")
        lines.append(f"        approve: {approve_text(bundle)}")
    text = [bundle.manifest["description"], "", "Args:", *[f"    {l.strip()}" for l in lines], "",
            "Returns a dict with status 'ok' and the outputs, 'needs_approval', or 'error'."]
    body = "\n".join(("    " + l) if l else "" for l in text)
    body = body.replace("\\", "\\\\").replace('"""', "'''")
    names = [n for n, _ in ordered_inputs(bundle)]
    call = "{" + ", ".join(f"{n!r}: {n}" for n in names) + "}"
    approve_arg = "approve" if gated(bundle) else "True"
    annotations = {n: _annotation(spec) for n, spec in ordered_inputs(bundle)}
    if gated(bundle):
        annotations["approve"] = "bool"
    annotations["return"] = "dict"
    pinned = "{" + ", ".join(f"{k!r}: {v}" for k, v in annotations.items()) + "}"
    return (
        f"def {name}({', '.join(params)}) -> dict:\n"
        f'    """\n{body}\n    """\n'
        f"    return _invoke({call}, {approve_arg})\n\n\n"
        "# An agent may compile this file with `from __future__ import annotations` in force, which turns the\n"
        "# annotations above into text and makes every parameter look like a string. Pin the real types.\n"
        f"{name}.__annotations__ = {pinned}\n"
    )


def agent_pack(bundle: Bundle) -> tuple[dict[str, str], list[str]]:
    manifest = bundle.manifest
    name = manifest["id"]
    if not TOOL_NAME_RE.match(name):
        raise ValueError(
            f"'{name}' cannot be an agent tool name: use 3 to 64 lowercase letters, digits or underscores, "
            "starting with a letter. Change the workflow id."
        )
    embedded = {
        "workflow": bundle.workflow,
        "capabilities": bundle.capabilities,
        "bases": bundle.bases,
        "engines": bundle.engines,
    }
    from ..bundle import PORTABLE_SOURCE

    tool = (
        TEMPLATE.replace("__PORTABLE__", repr(PORTABLE_SOURCE.read_text(encoding="utf-8")))
        .replace("__BUNDLE__", repr(json.dumps(embedded, sort_keys=True)))
        .replace("__GATED__", repr(gated(bundle)))
        .replace("__APPROVE_MESSAGE__", repr(approve_text(bundle) if gated(bundle) else ""))
        .replace("__NAME__", name)
        .replace("__FUNCTION__", _function(name, bundle))
    )
    example = {
        n: (spec.get("default") if "default" in spec else f"<{spec['type']}>")
        for n, spec in manifest["inputs"].items()
    }
    env_names = list(manifest["requires"].get("env", []))
    plugin = {
        "name": name,
        "version": manifest["version"],
        "type": "tool_pack",
        "description": manifest["description"],
        "tools": [
            {
                "name": name,
                "file": f"tools/{name}.py",
                "description": manifest["description"],
                "params_note": json.dumps(example, ensure_ascii=False),
                "env_vars": env_names,
            }
        ],
    }
    readme = _readme(bundle, name, env_names)
    files = {
        "plugin.yaml": yaml.safe_dump(plugin, sort_keys=False, allow_unicode=True),
        f"tools/{name}.py": tool,
        "env.example": "".join(f"{e}=\n" for e in env_names),
        "README.md": readme,
    }
    notes = [
        "Install by hand on the agent's machine: /agent pack install <this folder>.",
        "The tool is a single synchronous function; the agent runs it in a worker thread with no time limit.",
    ]
    if gated(bundle):
        notes.append(
            "Approval is enforced by a parameter, not by the agent: the tool refuses to start until it is called with "
            "approve=true, and its description tells the model to ask the user first. A model that ignores that "
            "instruction can still pass approve=true."
        )
    notes += bundle.warnings
    if manifest["requires"].get("packages"):
        notes.append("Install these Python packages in the agent's environment: " + ", ".join(manifest["requires"]["packages"]))
    return files, notes


def _readme(bundle: Bundle, name: str, env_names: list[str]) -> str:
    manifest = bundle.manifest
    out = [f"# {manifest['name']}", "", manifest["description"], "", "## Install", "",
           f"```\n/agent pack install <path to this folder>\n```", "",
           f"The tool is called `{name}`. It is one Python file and needs nothing from the workflow factory.", ""]
    if env_names:
        out += ["## Environment variables", "", *[f"- `{e}`" for e in env_names], "",
                "Names only, in `env.example`; set the values in the agent's environment.", ""]
    if manifest["requires"].get("binaries"):
        out += ["## Programs that must be installed", "", *[f"- `{b}`" for b in manifest["requires"]["binaries"]], ""]
    if manifest["requires"].get("packages"):
        out += ["## Python packages", "", *[f"- `{p}`" for p in manifest["requires"]["packages"]], ""]
    if manifest["external"]:
        out += ["## Engines this tool expects on the machine", ""]
        for item in manifest["external"]:
            out.append(f"- `{item['capability']}` (a folder named `{item['folder'].split('/', 1)[1]}`). "
                       f"Set `{item['override_env']}` to the folder that holds it.")
        out.append("")
    file_inputs = [n for n, s in manifest["inputs"].items() if is_file(s)]
    if file_inputs:
        out += ["## File inputs", "", f"`{', '.join(file_inputs)}` accept {FILE_FORMS}. "
                "Local paths are refused unless the folder is listed in `STUDIO_FILE_ROOTS`. "
                "Downloads are https only, limited to public hosts and to `STUDIO_MAX_FILE_MB` (default 100).", ""]
    if gated(bundle):
        out += ["## Approval", "", approve_text(bundle), ""]
    out += ["## Where runs go", "", "`STUDIO_TOOL_HOME` (default: the system temp folder, `studio_tools/`). "
            "Each call gets its own run folder, returned as `run_folder`.", ""]
    return "\n".join(out)


AGENT_NAME_RE = TOOL_NAME_RE  # the agent app uses the same rule for agent names

PROMPT = """You run exactly one tool, `{tool}`, and nothing else.

{about}

Rules:
- Call `{tool}` with the inputs the task gives you. Do not invent values for inputs the task does not give; ask for them instead.
- Give back the tool's result as it is. Do not rewrite, round or embellish numbers and text it returns.
- If the tool returns an error, report the error text as it is.
{approval}"""


def agent_bundle(bundle: Bundle) -> tuple[dict[str, str], list[str]]:
    """A pack with the tool **and** a small agent that owns it.

    An installed tool is only a registry entry: the orchestrator cannot call it until some
    sub-agent has it in its tool list. This bundle adds that agent, so installing the pack is enough
    for the orchestrator to delegate to the workflow.
    """

    files, notes = agent_pack(bundle)
    manifest = bundle.manifest
    tool = manifest["id"]
    agent = f"{tool}_agent"
    if not AGENT_NAME_RE.match(agent):
        raise ValueError(
            f"'{agent}' cannot be an agent name: use 3 to 64 lowercase letters, digits or underscores. "
            "Shorten the workflow id."
        )
    plugin = yaml.safe_load(files["plugin.yaml"])
    plugin["type"] = "agent_bundle"
    plugin["agents"] = [f"agents/{agent}.yaml"]
    files["plugin.yaml"] = yaml.safe_dump(plugin, sort_keys=False, allow_unicode=True)
    approval = (
        "- This tool changes something outside the machine. Never set `approve` to true unless the task says in so many words "
        "that the user approved it.\n"
        if gated(bundle) else ""
    )
    files[f"agents/{agent}.yaml"] = yaml.safe_dump(
        {
            "name": agent,
            "type": "config",
            "enabled": True,
            "description": f"{manifest['description']} Delegate to this agent to run the `{tool}` workflow.",
            "model": "default",
            "tool_mode": "custom",
            "tools": [tool],
            "system_prompt_file": f"prompts/{agent}.md",
        },
        sort_keys=False, allow_unicode=True,
    )
    files[f"prompts/{agent}.md"] = PROMPT.format(tool=tool, about=manifest["description"], approval=approval)
    files["README.md"] = files["README.md"].rstrip("\n") + (
        f"\n\n## The agent\n\nThis pack is an `agent_bundle`: besides the tool it adds a sub-agent named `{agent}` that owns it, "
        f"so the orchestrator can delegate to `{agent}` to run the workflow. The agent reads its sub-agents at start-up, "
        "so restart it after installing.\n"
    )
    notes = [n for n in notes if not n.startswith("Install by hand")]
    notes.insert(0, f"Install with /agent pack install <this folder>, then restart the agent: it adds the agent `{agent}`, which owns the tool.")
    return files, notes
