"""Job handler: the workflow as one item any worker can call.

``handler.py`` is a single self-contained file (standard library only; the
runner, workflow, capabilities and single-file engines are embedded). It does
not poll, queue or listen: a worker that already has jobs calls it.

    import handler
    result = handler.handle(job["payload"]["inputs"], approved_steps=job.get("approved_steps", []))

or, from a worker in any language, as a process:

    echo '{"inputs": {...}, "approved_steps": []}' | python handler.py

``handle`` returns ``{"status": "done" | "awaiting_approval" | "failed", ...}``.
Approval is **per step**: a step that writes to the outside world only runs when
its id is in ``approved_steps``; until then nothing runs at all.
"""

from __future__ import annotations

import json

from ..bundle import PORTABLE_SOURCE, Bundle
from ._common import gated
from .tool_schema import input_schema

TEMPLATE = '''# Generated by the workflow factory. Edit the source workflow, not this file.
"""Handler for the workflow __ACTION__.

Contract:
    handle(inputs, approved_steps=(), workdir=None, log=None) -> dict
    python handler.py < {"inputs": {...}, "approved_steps": [...]}  > result.json

Result: {"status": "done", "outputs": {...}, "run_folder": "..."}
        {"status": "awaiting_approval", "gated_steps": [...], "message": "..."}
        {"status": "failed", "error": "..."}
Standard library only.
"""
import hashlib
import json
import os
import sys
import tempfile
import time
import types
from pathlib import Path

ACTION = "__ACTION__"
MANIFEST = json.loads(__MANIFEST__)
INPUT_SCHEMA = json.loads(__SCHEMA__)
GATED_STEPS = MANIFEST["gated_steps"]
_PORTABLE_SOURCE = __PORTABLE__
_BUNDLE = json.loads(__BUNDLE__)
_runner = None


def _load_runner():
    global _runner
    if _runner is None:
        module = types.ModuleType("studio_portable")
        sys.modules["studio_portable"] = module
        exec(compile(_PORTABLE_SOURCE, "studio_portable.py", "exec"), module.__dict__)
        _runner = module
    return _runner


def _home():
    digest = hashlib.sha1(json.dumps(_BUNDLE, sort_keys=True).encode()).hexdigest()[:8]
    base = Path(os.environ.get("STUDIO_TOOL_HOME") or Path(tempfile.gettempdir()) / "studio_tools")
    root = base / ACTION / digest
    for relative, source in _BUNDLE["engines"].items():
        target = root / relative
        if not target.exists():
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(source, encoding="utf-8")
    return root


def handle(inputs, approved_steps=(), workdir=None, log=None):
    approved = set(approved_steps or ())
    waiting = [g for g in GATED_STEPS if g["step"] not in approved]
    if waiting:
        return {
            "status": "awaiting_approval",
            "gated_steps": waiting,
            "message": "These steps change something outside the machine and have not been approved: "
            + ", ".join(g["step"] + " (" + g["capability"] + ")" for g in waiting) + ". Nothing was run.",
        }
    try:
        runner = _load_runner()
        root = _home()
        bases = {cid: (Path(p) if Path(p).is_absolute() else root / p) for cid, p in _BUNDLE["bases"].items()}
        folder = Path(workdir) if workdir else root / "runs" / time.strftime("%Y%m%d_%H%M%S")
        result = runner.run(
            _BUNDLE["workflow"], _BUNDLE["capabilities"], bases, dict(inputs or {}), folder,
            approve=lambda step, cap: step in approved, log=log or (lambda message: None),
            files=runner.FilePolicy.from_env(),
        )
        return {"status": "done", "outputs": result.outputs, "run_folder": str(folder)}
    except Exception as error:  # a worker should record the reason, not die
        return {"status": "failed", "error": f"{type(error).__name__}: {error}"}


def main():
    try:
        request = json.load(sys.stdin)
        if not isinstance(request, dict):
            raise ValueError("expected a JSON object")
        unexpected = sorted(set(request) - {"inputs", "approved_steps"})
        if unexpected:
            raise ValueError("unexpected field(s): " + ", ".join(unexpected))
    except ValueError as error:
        print(json.dumps({"status": "failed", "error": f"bad request: {error}"}))
        return 1
    result = handle(request.get("inputs"), request.get("approved_steps") or ())
    print(json.dumps(result, default=str))
    return 0 if result["status"] != "failed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
'''


def handler_source(bundle: Bundle) -> str:
    embedded = {
        "workflow": bundle.workflow,
        "capabilities": bundle.capabilities,
        "bases": bundle.bases,
        "engines": bundle.engines,
    }
    return (
        TEMPLATE.replace("__PORTABLE__", repr(PORTABLE_SOURCE.read_text(encoding="utf-8")))
        .replace("__BUNDLE__", repr(json.dumps(embedded, sort_keys=True)))
        .replace("__MANIFEST__", repr(json.dumps(bundle.manifest, sort_keys=True)))
        .replace("__SCHEMA__", repr(json.dumps(input_schema(bundle))))
        .replace("__ACTION__", bundle.manifest["id"])
    )


def job_handler(bundle: Bundle) -> tuple[dict[str, str], list[str]]:
    manifest = bundle.manifest
    files = {
        "handler.py": handler_source(bundle),
        "job.schema.json": json.dumps(
            {"type": "object", "properties": {"inputs": input_schema(bundle)}, "required": ["inputs"],
             "additionalProperties": False},
            indent=2, ensure_ascii=False,
        ) + "\n",
        "README.md": _readme(bundle),
    }
    notes = [
        "handler.py does not poll or listen: an existing worker has to call it (import it, or run it as a process).",
        "Approval is per step and enforced by the handler: a gated step runs only when its id is in approved_steps. "
        "Who may set approved_steps is up to the worker and its queue.",
    ]
    if manifest["requires"].get("packages"):
        notes.append("Install these Python packages where the worker runs: " + ", ".join(manifest["requires"]["packages"]))
    return files, notes + bundle.warnings


def _readme(bundle: Bundle) -> str:
    manifest = bundle.manifest
    steps = ", ".join(f"`{g['step']}`" for g in gated(bundle)) or "none"
    return f"""# {manifest['name']} (job handler)

{manifest['description']}

`handler.py` is one file, standard library only. It is an item to plug into a worker you already run.

## From a Python worker

```python
import handler
result = handler.handle(job["payload"]["inputs"], approved_steps=job.get("approved_steps", []))
```

## From a worker in any language

```
echo '{{"inputs": {{...}}, "approved_steps": []}}' | python handler.py
```

Exit code 0 unless the status is `failed`; the result is one JSON object on stdout.

## Result

- `{{"status": "done", "outputs": ..., "run_folder": ...}}`
- `{{"status": "awaiting_approval", "gated_steps": [...]}}`: nothing ran
- `{{"status": "failed", "error": ...}}`

## Approval

Steps that change something outside the machine: {steps}. They run only when their id is in `approved_steps`.
Decide in your worker who is allowed to add to that list; the handler only checks it.

`job.schema.json` describes the request. File inputs follow the rules in the factory's docs/adapters.md
(`STUDIO_FILE_ROOTS`, https only, size limit).
"""
