"""MCP server: the workflow as one tool of a Model Context Protocol server.

Produces ``server.py`` (standard library only, speaks MCP over stdio) and the
``handler.py`` it calls. Any MCP client can launch it as a command:

    {"mcpServers": {"<workflow>": {"command": "python", "args": ["/path/server.py"]}}}

It exposes exactly one tool, named after the workflow. Approval is a tool
argument (``approve``), the same convention as the agent pack: a convention the
client must respect, not a lock. For a lock, use the worker adapter.
"""

from __future__ import annotations

import json

from ..bundle import Bundle
from ._common import approve_text, gated
from .job_handler import handler_source
from .tool_schema import input_schema

SERVER = '''# Generated by the workflow factory. Edit the source workflow, not this file.
"""MCP server (stdio) for the workflow __ACTION__. Standard library only.

    python server.py

Speaks newline-delimited JSON-RPC 2.0 on stdin/stdout. Everything the engines
print is sent to stderr so it cannot corrupt the protocol.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import handler  # noqa: E402

PROTOCOLS = ["2025-06-18", "2025-03-26", "2024-11-05"]
TOOL = json.loads(__TOOL__)
GATED = [g["step"] for g in handler.GATED_STEPS]


def _truthy(value):
    # a client may hand over "false" as text, and bool("false") is True
    if isinstance(value, str):
        return value.strip().lower() in ("true", "1", "yes", "y")
    return bool(value)


def call_tool(arguments):
    arguments = dict(arguments or {})
    approve = _truthy(arguments.pop("approve", False))
    result = handler.handle(arguments, approved_steps=GATED if approve else (), log=lambda m: print(m, file=sys.stderr))
    text = json.dumps(result, ensure_ascii=False, default=str)
    return {"content": [{"type": "text", "text": text}], "isError": result["status"] == "failed"}


def respond(message):
    method, params = message.get("method"), message.get("params") or {}
    if method == "initialize":
        asked = params.get("protocolVersion")
        return {
            "protocolVersion": asked if asked in PROTOCOLS else PROTOCOLS[0],
            "capabilities": {"tools": {"listChanged": False}},
            "serverInfo": {"name": TOOL["name"], "version": handler.MANIFEST.get("version", "0.0.0")},
        }
    if method == "ping":
        return {}
    if method == "tools/list":
        return {"tools": [TOOL]}
    if method == "tools/call":
        if params.get("name") != TOOL["name"]:
            raise ValueError("unknown tool: " + str(params.get("name")))
        return call_tool(params.get("arguments"))
    raise LookupError(method)


def serve(stdin, stdout):
    for line in stdin:
        line = line.strip()
        if not line:
            continue
        try:
            message = json.loads(line)
            if not isinstance(message, dict):
                raise ValueError("expected an object")
        except ValueError:
            stdout.write(json.dumps({"jsonrpc": "2.0", "id": None, "error": {"code": -32700, "message": "parse error"}}) + "\\n")
            stdout.flush()
            continue
        if "id" not in message:  # a notification: no answer, whatever it is
            continue
        reply = {"jsonrpc": "2.0", "id": message["id"]}
        try:
            reply["result"] = respond(message)
        except LookupError as error:
            reply["error"] = {"code": -32601, "message": "method not found: " + str(error)}
        except ValueError as error:
            reply["error"] = {"code": -32602, "message": str(error)}
        except Exception as error:  # keep serving
            reply["error"] = {"code": -32603, "message": type(error).__name__ + ": " + str(error)}
        stdout.write(json.dumps(reply, ensure_ascii=False) + "\\n")
        stdout.flush()


if __name__ == "__main__":
    protocol = sys.stdout
    sys.stdout = sys.stderr  # a print() inside an engine must not reach the client
    serve(sys.stdin, protocol)
'''


def tool_definition(bundle: Bundle) -> dict:
    manifest = bundle.manifest
    description = manifest["description"]
    if gated(bundle):
        description += " " + approve_text(bundle)
    return {
        "name": manifest["id"],
        "description": description,
        "inputSchema": input_schema(bundle, approve_param=True),
        "annotations": {
            "title": manifest["name"],
            "readOnlyHint": False,
            "destructiveHint": bool(gated(bundle)),
            "openWorldHint": bool(manifest["permissions"].get("network")),
        },
    }


def mcp_server(bundle: Bundle) -> tuple[dict[str, str], list[str]]:
    manifest = bundle.manifest
    action = manifest["id"]
    files = {
        "server.py": SERVER.replace("__TOOL__", repr(json.dumps(tool_definition(bundle)))).replace("__ACTION__", action),
        "handler.py": handler_source(bundle),
        "mcp.json": json.dumps(
            {"mcpServers": {action: {"command": "python", "args": ["server.py"], "env": {}}}}, indent=2
        ) + "\n",
        "README.md": _readme(bundle),
    }
    notes = [
        "server.py speaks MCP over stdio only: the client starts it as a command. It is not an HTTP server.",
        "One tool, named after the workflow. Runs are synchronous; a long run blocks the server until it ends.",
    ]
    if gated(bundle):
        notes.append(
            "Approval is the tool argument 'approve': a convention the client must respect. "
            "Use the worker adapter when approval has to be enforced."
        )
    if manifest["requires"].get("packages"):
        notes.append("Install these Python packages where the server runs: " + ", ".join(manifest["requires"]["packages"]))
    return files, notes + bundle.warnings


def _readme(bundle: Bundle) -> str:
    manifest = bundle.manifest
    steps = ", ".join(f"`{g['step']}`" for g in gated(bundle)) or "none"
    return f"""# {manifest['name']} (MCP server)

{manifest['description']}

`server.py` is a Model Context Protocol server over stdio. Standard library only; it calls `handler.py` in the same folder.

## Use it

Register it with any MCP client as a command. `mcp.json` has the entry; change `server.py` to the absolute path:

```json
{json.dumps({"mcpServers": {manifest['id']: {"command": "python", "args": ["/absolute/path/server.py"]}}}, indent=2)}
```

It offers one tool, `{manifest['id']}`. Its arguments are the workflow inputs.

## Result

The tool returns one JSON text block: `{{"status": "done", "outputs": ..., "run_folder": ...}}`,
`{{"status": "awaiting_approval", ...}}` (nothing ran) or `{{"status": "failed", "error": ...}}` (`isError` is set).

## Approval

Steps that change something outside the machine: {steps}. They run only when the call has `approve: true`,
and a model is told to set it only after the user said yes. That is a convention the client has to respect.

File inputs follow the rules in the factory's docs/adapters.md (`STUDIO_FILE_ROOTS`, https only, size limit).
"""
