"""Worker: the workflow as a standalone process that serves a job queue.

Produces a folder with ``worker.py`` (standard library only), the
``handler.py`` it calls, a Supabase migration in the same shape as the
``*_jobs`` tables of the existing workers, a Dockerfile and a README.

Two queues: a ``file`` queue (folders on disk, nothing to install) and a
``supabase`` queue (PostgREST over HTTPS, same claim pattern as the other
workers: an RPC that claims one row with ``for update skip locked``).

Approval is held by the queue: a job for a workflow with gated steps goes to
``awaiting_approval`` and runs only after someone with write access to the
queue lists the steps in ``approved_steps``.
"""

from __future__ import annotations

import json
import re

from ..bundle import Bundle
from ._common import gated
from .job_handler import handler_source
from .tool_schema import input_schema

WORKER = '''# Generated by the workflow factory. Edit the source workflow, not this file.
"""Queue worker for the workflow __ACTION__. Standard library only.

    python worker.py            # serve the queue until stopped
    python worker.py --once     # process what is queued, then exit

Environment:
    WORKER_BACKEND   file (default) or supabase
    WORKER_DIR       file queue folder (default ./queue)
    SUPABASE_URL, SUPABASE_SECRET_KEY    for the supabase queue
    WORKER_POLL_MS   wait between empty polls (default 5000)
"""
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import handler  # noqa: E402

TABLE = "__TABLE__"
SECRET_NAME = re.compile(r"(KEY|SECRET|TOKEN|PASSWORD|REFRESH|BEARER)", re.IGNORECASE)


def log(message):
    print("[__ACTION__-worker] " + message, flush=True)


def _now():
    return datetime.now(timezone.utc).isoformat()


def redact(payload):
    """Secret-looking environment values must never reach a result stored in the queue."""
    secrets = sorted(
        {v for k, v in os.environ.items() if SECRET_NAME.search(k) and len(v) >= 8}, key=len, reverse=True
    )
    if not secrets:
        return payload
    text = json.dumps(payload, ensure_ascii=False, default=str)
    for secret in secrets:
        text = text.replace(secret, "[redacted]").replace(json.dumps(secret)[1:-1], "[redacted]")
    return json.loads(text)


class FileQueue:
    """Jobs are JSON files that move between folders. Claiming is an atomic rename."""

    STATES = ("queued", "processing", "awaiting_approval", "done", "failed")

    def __init__(self, root):
        self.root = Path(root)
        for state in self.STATES:
            (self.root / state).mkdir(parents=True, exist_ok=True)

    def _path(self, state, job):
        return self.root / state / (job["id"] + ".json")

    def claim_next(self):
        for candidate in sorted((self.root / "queued").glob("*.json"), key=lambda p: p.stat().st_mtime):
            target = self.root / "processing" / candidate.name
            try:
                candidate.rename(target)
            except OSError:
                continue  # another worker took it
            job = json.loads(target.read_text(encoding="utf-8"))
            job.setdefault("id", candidate.stem)
            job["attempts"] = int(job.get("attempts", 0)) + 1
            job["started_at"] = _now()
            return job
        return None

    def _move(self, job, state, **fields):
        job.update(fields, status=state, updated_at=_now())
        target = self._path(state, job)
        target.write_text(json.dumps(job, indent=2, default=str), encoding="utf-8")
        old = self._path("processing", job)
        if old != target:
            old.unlink(missing_ok=True)

    def finish(self, job, results):
        self._move(job, "done", results=results, error=None, completed_at=_now())

    def fail(self, job, error, results=None):
        self._move(job, "failed", results=results or {}, error=str(error)[:2000], completed_at=_now())

    def hold(self, job, results):
        self._move(job, "awaiting_approval", results=results, error=None)


class SupabaseQueue:
    """The <table> table over Supabase's REST API; same claim pattern as the other workers."""

    def __init__(self):
        self.url = (os.getenv("SUPABASE_URL") or "").strip().rstrip("/")
        self.key = (os.getenv("SUPABASE_SECRET_KEY") or os.getenv("SUPABASE_SERVICE_ROLE_KEY") or "").strip()
        if not self.url or not self.key:
            raise SystemExit("SUPABASE_URL and SUPABASE_SECRET_KEY must be set for the supabase queue")

    def _request(self, method, path, body=None, params=""):
        request = urllib.request.Request(
            f"{self.url}/rest/v1/{path}{params}",
            data=json.dumps(body if body is not None else {}).encode() if method != "GET" else None,
            method=method,
            headers={"apikey": self.key, "Authorization": "Bearer " + self.key, "Content-Type": "application/json"},
        )
        try:
            with urllib.request.urlopen(request, timeout=20) as response:
                raw = response.read()
                return json.loads(raw) if raw else None
        except (urllib.error.URLError, ValueError) as error:
            raise ConnectionError(f"{method} {path} failed: {error}") from error

    def claim_next(self):
        job = self._request("POST", "rpc/claim_" + TABLE.removesuffix("s"), {})
        return job if isinstance(job, dict) and job.get("id") else None

    def _patch(self, job, patch):
        self._request("PATCH", TABLE, patch, params="?id=eq." + str(job["id"]))

    def finish(self, job, results):
        now = _now()
        self._patch(job, {"status": "done", "results": results, "error": None, "completed_at": now, "updated_at": now})

    def fail(self, job, error, results=None):
        now = _now()
        self._patch(job, {"status": "failed", "results": results or {}, "error": str(error)[:2000],
                          "completed_at": now, "updated_at": now})

    def hold(self, job, results):
        self._patch(job, {"status": "awaiting_approval", "results": results, "error": None, "updated_at": _now()})


def process(job, queue):
    payload = job.get("payload") if isinstance(job.get("payload"), dict) else {}
    unexpected = sorted(set(payload) - {"inputs"})
    if unexpected:
        queue.fail(job, f"unexpected field(s) in payload: {unexpected}")
        return "failed"
    result = redact(handler.handle(payload.get("inputs") or {}, approved_steps=job.get("approved_steps") or []))
    status = result["status"]
    if status == "done":
        queue.finish(job, result)
        return "done"
    if status == "awaiting_approval":
        queue.hold(job, result)
        return "awaiting_approval"
    queue.fail(job, result.get("error") or "workflow failed", result)
    return "failed"


def run_once(queue):
    job = queue.claim_next()
    if not job:
        return False
    try:
        outcome = process(job, queue)
    except Exception as error:  # never leave a claimed job stuck in 'processing'
        log(f"job {job.get('id')} crashed: {type(error).__name__}: {error}")
        queue.fail(job, "worker error: " + type(error).__name__)
        return True
    log(f"job {job.get('id')}: {outcome}")
    return True


def make_queue():
    backend = (os.getenv("WORKER_BACKEND") or "file").lower()
    if backend == "supabase":
        return SupabaseQueue()
    if backend == "file":
        return FileQueue(os.getenv("WORKER_DIR") or "queue")
    raise SystemExit("WORKER_BACKEND must be 'file' or 'supabase'")


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    queue = make_queue()
    poll = max(0.2, int(os.getenv("WORKER_POLL_MS") or 5000) / 1000)
    log("started (" + (os.getenv("WORKER_BACKEND") or "file") + " queue)")
    while True:
        try:
            while run_once(queue):
                pass
        except ConnectionError as error:
            log(f"queue error: {error}")
        if "--once" in argv:
            return 0
        time.sleep(poll)


if __name__ == "__main__":
    raise SystemExit(main())
'''

MIGRATION = """-- {table}: the queue between whatever asks for the workflow "{action}" and
-- the worker that runs it. Same shape and claim pattern as platform_data_jobs /
-- publish_jobs. `payload` is {{"inputs": {{...}}}} (see job.schema.json).
--
-- Steps that change something outside the machine ({gated}) only run once their
-- ids are listed in `approved_steps`. A job waits in 'awaiting_approval' until
-- an operator adds them and sets the status back to 'queued'.
create table if not exists {table} (
  id uuid primary key default gen_random_uuid(),
  owner_ref text,
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'awaiting_approval', 'done', 'failed')),
  payload jsonb not null,
  approved_steps jsonb not null default '[]'::jsonb,
  results jsonb not null default '{{}}'::jsonb,
  error text,
  attempts integer not null default 0,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists {table}_status_created_idx on {table}(status, created_at);
alter table {table} enable row level security;

create or replace function {claim}()
returns {table}
language plpgsql
as $$
declare claimed {table};
begin
  with candidate as (
    select id from {table} where status = 'queued'
    order by created_at asc for update skip locked limit 1
  )
  update {table} job set
    status = 'processing', attempts = job.attempts + 1,
    started_at = now(), updated_at = now(), error = null
  from candidate where job.id = candidate.id
  returning job.* into claimed;
  return claimed;
end;
$$;

-- ---------------------------------------------------------------------------
-- Least privilege. The party that asks for the workflow (an agent, an app) must
-- only be able to insert a payload and read results: it must NOT be able to
-- write `approved_steps` or `status`, otherwise it could approve itself.
-- Not applied automatically; adapt the role names, then run.
--
-- grant select on {table} to marketing_agent_writer;
-- grant insert (owner_ref, payload) on {table} to marketing_agent_writer;
-- create policy requester_select on {table} for select to marketing_agent_writer using (true);
-- create policy requester_insert on {table} for insert to marketing_agent_writer with check (true);
--
-- Approving, as an operator (service key or an operator role):
--   update {table} set approved_steps = '["step_id"]', status = 'queued' where id = '<job id>';
"""


def _table(action: str) -> str:
    return re.sub(r"\W", "_", action) + "_jobs"


def worker(bundle: Bundle) -> tuple[dict[str, str], list[str]]:
    action = bundle.manifest["id"]
    table = _table(action)
    claim = "claim_" + table[: -len("s")]
    steps = ", ".join(g["step"] for g in gated(bundle)) or "none"
    env_names = list(bundle.manifest["requires"].get("env", []))
    files = {
        "worker.py": WORKER.replace("__ACTION__", action).replace("__TABLE__", table),
        "handler.py": handler_source(bundle),
        "job.schema.json": json.dumps(
            {"type": "object", "properties": {"inputs": input_schema(bundle)}, "required": ["inputs"],
             "additionalProperties": False}, indent=2, ensure_ascii=False) + "\n",
        f"migrations/001_{table}.sql": MIGRATION.format(table=table, action=action, claim=claim, gated=steps),
        ".env.example": "WORKER_BACKEND=file\nWORKER_DIR=queue\nWORKER_POLL_MS=5000\n"
        "# STUDIO_FILE_ROOTS=/folders/jobs/may/read\n# STUDIO_PYTHON=/path/to/venv/bin/python\n"
        "# for WORKER_BACKEND=supabase:\n# SUPABASE_URL=\n# SUPABASE_SECRET_KEY=\n"
        + "".join(f"{name}=\n" for name in env_names),
        "Dockerfile": "FROM python:3.12-slim\nWORKDIR /app\nCOPY . /app\n"
        + ("RUN pip install --no-cache-dir -r requirements.txt\n" if bundle.requirements else "")
        + 'CMD ["python", "worker.py"]\n',
        "README.md": _readme(bundle, action, table, steps),
    }
    if bundle.requirements:
        files["requirements.txt"] = "".join(f"{p}\n" for p in bundle.requirements)
    notes = [
        "Run it with: python worker.py (WORKER_BACKEND=file needs nothing else; supabase needs the migration applied).",
        "The worker is one process that runs one job at a time.",
    ]
    if gated(bundle):
        notes.append(
            "Approval is held by the queue: a job waits in awaiting_approval until approved_steps lists the gated steps. "
            "That is only a real gate if the party that creates jobs cannot write approved_steps or status "
            "(the migration shows the grants; the file queue relies on who can write to its folders)."
        )
    notes += bundle.warnings
    return files, notes


def _readme(bundle: Bundle, action: str, table: str, steps: str) -> str:
    manifest = bundle.manifest
    return f"""# {manifest['name']} (worker)

{manifest['description']}

A standalone worker for the workflow `{action}`. It takes jobs from a queue, runs the workflow for each, and
writes the result back. Standard library only; `handler.py` holds the workflow and is the same file you can
plug into any other worker.

## Run

```bash
cp .env.example .env
python worker.py            # serve the queue
python worker.py --once     # process what is queued and exit
```

### File queue (default, nothing to install)

Drop a JSON file into `queue/queued/`:

```json
{{"id": "job-1", "payload": {{"inputs": {{}}}}}}
```

Jobs move through `queued/`, `processing/`, `awaiting_approval/`, `done/` and `failed/`. The finished file has
`results`. Claiming is an atomic rename, so several workers can share one folder.

### Supabase queue

Apply `migrations/001_{table}.sql`, set `WORKER_BACKEND=supabase`, `SUPABASE_URL` and `SUPABASE_SECRET_KEY`, and
insert rows into `{table}` with `payload = {{"inputs": {{...}}}}`. The result is in `results`; a failure also fills `error`.

## Job

`payload` must be `{{"inputs": {{...}}}}` and nothing else (see `job.schema.json`). Unknown fields fail the job.
File inputs follow the factory's rules: https addresses, base64 objects, or paths under `STUDIO_FILE_ROOTS`.

## Approval

Steps that change something outside the machine: {steps}.

A job for this workflow does **not** run them until they are approved. It stops in `awaiting_approval` and
nothing at all runs. To approve, add the step ids to the job's `approved_steps` and put it back in `queued`:

- file queue: edit the file in `awaiting_approval/`, add `"approved_steps": ["step_id"]`, move it to `queued/`
- supabase: `update {table} set approved_steps = '["step_id"]', status = 'queued' where id = '<job id>';`

This is a real gate only when whoever creates jobs cannot do that. The migration shows the column grants.

## Needs on the machine

{_needs(manifest)}

Results have secret-looking environment values removed before they are stored.
"""


def _needs(manifest: dict) -> str:
    out = []
    for key, label in (("env", "Environment variables"), ("binaries", "Programs"), ("packages", "Python packages")):
        values = manifest["requires"].get(key) or []
        if values:
            out.append(f"- {label}: " + ", ".join(f"`{v}`" for v in values))
    for item in manifest["external"]:
        out.append(f"- Engine `{item['capability']}` (found at build time in `{item['found_at']}`; "
                   f"set `{item['override_env']}` if it lives elsewhere)")
    return "\n".join(out) or "- Nothing beyond Python."
