"""Free-form workflows.

A workflow is any directed acyclic graph of steps. Each step runs one
capability from the registry and wires its inputs from workflow inputs, from
the outputs of other steps, or from literal values. There is no limit on the
number of steps, no fixed set of step kinds, and no built-in list of which
capability may follow which: the only rules are the ones the capability
descriptions themselves state (types, required inputs, approval).

A workflow can then be exported as one capability, so it can be used as a
step in another workflow or handed to anything that reads capabilities.
"""

from __future__ import annotations

import copy
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .registry import Registry, load_registry

SPEC_VERSION = "0.1"
ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")
BASE_TYPES = {"any", "text", "integer", "number", "boolean", "enum", "url", "list", "object"}
REF_RE = re.compile(
    r"\{\{\s*(?:inputs\.([A-Za-z0-9_]+)|steps\.([A-Za-z0-9_]+)\.outputs\.([A-Za-z0-9_]+))\s*\}\}"
)
HEADER = "# Generated by the workflow factory. Edit the source workflow, not this file.\n"


class WorkflowError(ValueError):
    """The workflow is not valid. ``errors`` lists every problem found."""

    def __init__(self, errors: list[str]) -> None:
        super().__init__("; ".join(errors))
        self.errors = errors


@dataclass
class Analysis:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    order: list[str] = field(default_factory=list)
    needs: dict[str, list[str]] = field(default_factory=dict)
    caps: dict[str, dict[str, Any] | None] = field(default_factory=dict)
    approval: dict[str, bool] = field(default_factory=dict)
    output_types: dict[str, str] = field(default_factory=dict)


def load_workflow(path: Path) -> dict[str, Any]:
    doc = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise WorkflowError([f"{path}: expected a YAML mapping."])
    return doc


def valid_type(value: Any) -> bool:
    return isinstance(value, str) and (
        value in BASE_TYPES or re.fullmatch(r"file:[a-z0-9]+", value) is not None
    )


def compatible(produced: str | None, accepted: str) -> bool:
    return produced is None or produced == accepted or "any" in (produced, accepted)


def _literal_ok(value: Any, expected: str, spec: dict[str, Any]) -> bool:
    if expected == "any":
        return True
    if expected in {"text", "url"} or expected.startswith("file:"):
        return isinstance(value, str)
    if expected == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if expected == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if expected == "boolean":
        return isinstance(value, bool)
    if expected == "enum":
        return value in (spec.get("values") or [])
    if expected == "list":
        return isinstance(value, list)
    if expected == "object":
        return isinstance(value, dict)
    return False


def analyze(
    doc: dict[str, Any],
    registry: Registry | dict[str, dict[str, Any]],
    *,
    allow_unknown: bool = False,
) -> Analysis:
    """Check a workflow document and describe how it would run.

    With ``allow_unknown`` a step may use a capability the registry does not
    have yet (for example one that will be installed where the workflow runs).
    Such steps are not type checked and are assumed to write to the outside
    world, so they require approval.
    """

    result = Analysis()
    err = result.errors.append
    if not isinstance(doc, dict) or doc.get("spec_version") != SPEC_VERSION:
        err(f"spec_version must be '{SPEC_VERSION}'.")
        return result
    wf = doc.get("workflow")
    if not isinstance(wf, dict):
        err("Missing 'workflow' section.")
        return result
    if not ID_RE.match(str(wf.get("id", ""))):
        err("workflow.id must be lowercase letters, digits and underscores, starting with a letter.")
    if not str(wf.get("name", "")).strip():
        err("workflow.name is required.")

    inputs = wf.get("inputs") or {}
    for name, spec in inputs.items():
        if not isinstance(spec, dict) or not valid_type(spec.get("type")):
            err(f"inputs.{name}: invalid or missing type.")
        elif spec["type"] == "enum" and not spec.get("values"):
            err(f"inputs.{name}: an enum needs values.")

    steps = wf.get("steps")
    if not isinstance(steps, list) or not steps:
        err("A workflow needs at least one step.")
        return result
    by_id: dict[str, dict[str, Any]] = {}
    for step in steps:
        sid = str(step.get("id", ""))
        if not ID_RE.match(sid):
            err(f"Step id '{sid}' must be lowercase letters, digits and underscores.")
        elif sid in by_id:
            err(f"Duplicate step id '{sid}'.")
        by_id[sid] = step

    used_inputs: set[str] = set()
    deps: dict[str, set[str]] = {sid: set() for sid in by_id}

    for step in steps:
        sid = str(step.get("id", ""))
        where = f"step '{sid}'"
        cid = step.get("capability")
        cap = registry.get(cid) if cid else None
        result.caps[sid] = cap
        if cid is None:
            err(f"{where}: missing 'capability'.")
        elif cap is None:
            message = f"{where}: capability '{cid}' is not in the registry."
            if allow_unknown:
                result.warnings.append(message + " Assumed to write externally; its types are unchecked.")
            else:
                err(message + " Add its source, or validate with allow_unknown.")

        for needed in step.get("needs") or []:
            if needed not in by_id:
                err(f"{where}: needs unknown step '{needed}'.")
            elif needed == sid:
                err(f"{where}: cannot depend on itself.")
            else:
                deps[sid].add(needed)

        cap_inputs = (cap or {}).get("inputs") or {}
        given = step.get("with") or {}
        for key, value in given.items():
            spec = cap_inputs.get(key)
            if cap is not None and spec is None:
                err(f"{where}: '{key}' is not an input of '{cid}'.")
                continue
            expected = spec["type"] if spec else None
            refs = list(REF_RE.finditer(value)) if isinstance(value, str) else []
            for match in refs:
                name, ref_step, ref_out = match.groups()
                if name is not None:
                    used_inputs.add(name)
                    if name not in inputs:
                        err(f"{where}.{key}: workflow input '{name}' is not declared.")
                elif ref_step not in by_id:
                    err(f"{where}.{key}: refers to unknown step '{ref_step}'.")
                elif ref_step == sid:
                    err(f"{where}.{key}: a step cannot use its own output.")
                else:
                    deps[sid].add(ref_step)
            if refs and expected is not None:
                whole = len(refs) == 1 and refs[0].group(0) == value.strip()
                if whole:
                    produced = _ref_type(refs[0], inputs, result.caps, by_id)
                    if not compatible(produced, expected):
                        err(
                            f"{where}.{key}: needs {expected}, but {refs[0].group(0)} is {produced}. "
                            "Convert it with a step, or declare the type as 'any'."
                        )
                elif not compatible("text", expected):
                    err(f"{where}.{key}: text with embedded references can only fill a text input, not {expected}.")
            elif not refs and expected is not None and not _literal_ok(value, expected, spec):
                err(f"{where}.{key}: {value!r} is not a valid {expected}.")
        for key, spec in cap_inputs.items():
            if spec.get("required") and "default" not in spec and key not in given:
                err(f"{where}: required input '{key}' of '{cid}' has no value.")

        writes = cap is None and allow_unknown or bool(
            (cap or {}).get("permissions", {}).get("writes_external_state")
        )
        if step.get("approval") == "none" and writes:
            err(f"{where}: approval cannot be turned off for a step that writes to the outside world.")
        result.approval[sid] = writes or step.get("approval") == "required" or bool(
            (cap or {}).get("permissions", {}).get("requires_approval")
        )

    # order, cycle detection
    remaining = {sid: set(d) for sid, d in deps.items()}
    order: list[str] = []
    while remaining:
        ready = [sid for sid in by_id if sid in remaining and not remaining[sid]]
        if not ready:
            err("The steps form a cycle: " + ", ".join(sorted(remaining)) + ".")
            break
        for sid in ready:
            order.append(sid)
            del remaining[sid]
            for other in remaining.values():
                other.discard(sid)
    result.order = order
    result.needs = {sid: [s for s in by_id if s in deps[sid]] for sid in by_id}

    # outputs
    for name, value in (wf.get("outputs") or {}).items():
        match = REF_RE.fullmatch(str(value).strip())
        if not match:
            err(f"outputs.{name}: must be exactly one reference such as {{{{ steps.<step>.outputs.<name> }}}}.")
            continue
        used_inputs.add(match.group(1)) if match.group(1) else None
        produced = _ref_type(match, inputs, result.caps, by_id, errors=result.errors, where=f"outputs.{name}")
        result.output_types[name] = produced or "any"

    for name in inputs:
        if name not in used_inputs:
            result.warnings.append(f"Workflow input '{name}' is never used.")
    return result


def _ref_type(
    match: re.Match[str],
    inputs: dict[str, Any],
    caps: dict[str, dict[str, Any] | None],
    by_id: dict[str, Any],
    *,
    errors: list[str] | None = None,
    where: str = "",
) -> str | None:
    name, ref_step, ref_out = match.groups()
    if name is not None:
        spec = inputs.get(name)
        return spec.get("type") if isinstance(spec, dict) else None
    cap = caps.get(ref_step) if ref_step in by_id else None
    if cap is None:
        if errors is not None and ref_step not in by_id:
            errors.append(f"{where}: refers to unknown step '{ref_step}'.")
        return None
    out = (cap.get("outputs") or {}).get(ref_out)
    if out is None:
        message = f"{where or 'reference'}: '{cap['id']}' has no output '{ref_out}'."
        if errors is not None:
            errors.append(message)
        return None
    return out["type"]


def build_capability(
    doc: dict[str, Any], analysis: Analysis, registry: Registry | dict[str, dict[str, Any]]
) -> dict[str, Any]:
    wf = doc["workflow"]
    known = [c for c in analysis.caps.values() if c is not None]
    unknown = [sid for sid, c in analysis.caps.items() if c is None]

    def union(key: str) -> list[str]:
        values: list[str] = []
        for cap in known:
            for item in (cap.get("requires") or {}).get(key, []):
                if item not in values:
                    values.append(item)
        return values

    writes = bool(unknown) or any(c["permissions"]["writes_external_state"] for c in known)
    costs = [c["cost"]["estimate_usd"] for c in known]
    total_cost = None if unknown or any(c is None for c in costs) else sum(costs)
    outputs = {
        name: {"type": analysis.output_types.get(name, "any"), "description": f"Workflow output '{name}'."}
        for name in (wf.get("outputs") or {})
    }
    steps_text = ", ".join(s["capability"] for s in wf["steps"])
    return {
        "id": f"workflow.{wf['id']}",
        "version": str(wf.get("version", "0.1.0")),
        "title": wf["name"],
        "description": wf.get("description") or f"Runs {len(wf['steps'])} step(s): {steps_text}.",
        "status": "experimental",
        "inputs": dict(wf.get("inputs") or {}),
        "outputs": outputs,
        "requires": {"env": union("env"), "binaries": union("binaries"), "hardware": union("hardware")},
        "permissions": {
            "network": bool(unknown) or any(c["permissions"]["network"] for c in known),
            "writes_external_state": writes,
            "requires_approval": writes or any(c["permissions"]["requires_approval"] for c in known),
        },
        "cost": {
            "estimate_usd": total_cost,
            "notes": "Sum of the steps. Unknown (null) when any step is unmeasured or unresolved.",
        },
        "execution": {"type": "workflow", "definition": "workflow.yaml"},
        "failure_modes": [
            f"[{cap['id']}] {text}" for cap in known for text in cap.get("failure_modes", [])
        ]
        + [f"[{sid}] capability could not be resolved when this was exported." for sid in unknown],
    }


def build_files(
    doc: dict[str, Any],
    registry: Registry | dict[str, dict[str, Any]] | None = None,
    *,
    allow_unknown: bool = False,
) -> tuple[dict[str, str], list[str]]:
    """Validate and export. Returns ``({filename: text}, warnings)``."""

    registry = registry if registry is not None else load_registry()
    analysis = analyze(doc, registry, allow_unknown=allow_unknown)
    if analysis.errors:
        raise WorkflowError(analysis.errors)
    resolved = copy.deepcopy(doc)
    for step in resolved["workflow"]["steps"]:
        step["needs"] = analysis.needs[step["id"]]
        if analysis.approval[step["id"]]:
            step["approval"] = "required"
    capability_doc = {
        "spec_version": SPEC_VERSION,
        "capabilities": [build_capability(resolved, analysis, registry)],
    }
    files = {
        "workflow.yaml": HEADER + yaml.safe_dump(resolved, sort_keys=False, allow_unicode=True),
        "capability.yaml": HEADER + yaml.safe_dump(capability_doc, sort_keys=False, allow_unicode=True),
    }
    return files, analysis.warnings
